### ISSUE TITLE
Float numbers are exported as strings to google sheets

### ISSUE THREAD

**Issue by Dima564** [aiguofer/gspread-pandas#16]
MacOS High Sierra
gspread-pandas==1.0.3
pandas==0.22.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0

The result of exporting a data frame to Google Sheets:
`spread.df_to_sheet(tracked, index=False, sheet='Dashboard', start='A3', replace=True)`

[
![image](https://user-images.githubusercontent.com/2564019/38449876-d7ecbe1c-39c9-11e8-9bf5-77efbf49ca82.png)
](url)

Let me know if you need anything else!

**Comment by aiguofer** [comment]
Thanks for reporting! I actually noticed this a couple of days ago. I converted everything to unicode to work around an issue with objects that are non-json serilizable. I have an idea for a more robust solution which I'll try to play around with this weekend.

**Comment by aiguofer** [comment]
Well, turns out the fix was much easier than I was originally thinking. Instead of changing the JSON Encoder, which would have required changes to gspread, or doing the encoding myself, which would have required some fancy parsing depending on type, I simply changed how the Sheets API should interpret the values :)

**Comment by Dima564** [comment]
Thank you!
