### ISSUE TITLE
Error code 429. Quota exceeded for quota group 'ReadGroup' and limit 'USER-100s' of service

### ISSUE THREAD

**Issue by brunobasanta** [aiguofer/gspread-pandas#25]
Is there a plan to manage the excess of requests to the api? I need to do a massive reading of spreadsheets and I need to implement a backoff to manage the delay of requests to the api. I do not see in the documentation that has been solved previously, any idea?

**Comment by aiguofer** [comment]
Hey, thanks for reaching out!

I haven't encountered this, so I haven't really looked into it. I imagine there could be some sort of retry mechanism that increases the wait time between retries when the error is due to limits. Could you please provide some example of how you're trying to do this and what the error looks like? I should have some time to look into it in the next few days.

**Comment by aiguofer** [comment]
This is now available in the latest version 1.3.0
