### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by JonathanMair** [aiguofer/gspread-pandas#93]
Hi All

Thanks for this package, which is really useful. 

I have previously used gspread with service accounts without any problem, and have recently started using spread-pandas, which take a lot of work out of what I'm trying to do. However, I switched to using OAuth and it's giving me problems. 

The first time it authenticates fine, using the link, but the next time the script runs it doesn't ask for the link (which seems to indicate that it has found the creds directory), but then it throws this error. In development I can simply delete the creds directory and it will work again, but in the end I'll need to solve this. Any idea what I'm doing wrong?

The error message is: 

RefreshError: The credentials do not contain the necessary fields need to refresh the access token. You must specify refresh_token, token_uri, client_id, and client_secret.

Thanks for any advice!

**Comment by aiguofer** [comment]
Hi! Sorry for the delayed response. gspread-pandas stores your credentials in a file in the `$GSPREAD_PANDAS_CONFIG_DIR/creds` directory. The default `$GSPREAD_PANDAS_CONFIG_DIR` if none is provided is either `$XDG_CONFIG_HOME/gspread_pandas` or `$HOME/.config/gspread_pandas`. The file is named `default` by default (original, I know), or it's whatever name you provided while instantiating a `Client` or `Spread` object when you went through the oauth process. The file should be a simple JSON.

Your error tells me somehow one of those keys is missing, which I find hard to believe since the library explicitly puts those values in. Could you show me the content of the files in the `creds` directory inside the `gspread_pandas` config file? (remove actual secrets from it first)

**Comment by JonathanMair** [comment]
Hi - thanks very much for the reply -- and no need at all for an apology. I've slightly moved on from the project I was working on and no longer have the files. In the end I just worked with a service account and it was fine. When I get a chance I will try it again and if I can replicate the error I will get in touch. Best wishes
